# Assignment-1 (KNN Classifier)--PartB
## Breast cancer wisconsin dataset
In this assignment, we will build a KNN classifier that takes an features as as input and outputs a label 0 or 1.

The breast cancer dataset contains 569 samples with 30 real, positive features (including cancer mass attributes like mean radius, mean texture, mean perimeter, et cetera). Of the samples, 212 are labeled “malignant” and 357 are labeled “benign”. 
You can find more details in: https://scikit-learn.org/stable/datasets/index.html#breast-cancer-dataset

In [549]:
%matplotlib inline
import gzip, os
import numpy as np
import time
import pandas as pd
from sklearn.metrics import accuracy_score
from statistics import mode
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import confusion_matrix 

## Load the training set
data = load_breast_cancer()
X = data.data
y = data.target


In [550]:
## print some statistics on the dataset
### TODO YOUR CODE ###
df = pd.DataFrame(X)
dfy = pd.DataFrame(y)
# print("Total number of samples: ", )
print("Total number samples = ", X.shape[1]*X.shape[0])

# print the number of features per sample
print("print the number of features per sample")
print(df.count())

# Total number of classes
print("\nTotal number of classes = " , dfy[0].unique())

# print the number of samples in each class
train_digits, train_counts = np.unique(y, return_counts=True)
print("\nTraining set distribution:")
print(dict(zip(train_digits, train_counts)))


Total number samples =  17070
print the number of features per sample
0     569
1     569
2     569
3     569
4     569
5     569
6     569
7     569
8     569
9     569
10    569
11    569
12    569
13    569
14    569
15    569
16    569
17    569
18    569
19    569
20    569
21    569
22    569
23    569
24    569
25    569
26    569
27    569
28    569
29    569
dtype: int64

Total number of classes =  [0 1]

Training set distribution:
{0: 212, 1: 357}


In [551]:
from sklearn.model_selection import train_test_split
### TODO YOUR CODE ###
trainx, testx, trainy, testy = train_test_split(X,y,test_size=0.30,random_state=777)
testx, valx, testy, valy     = train_test_split(testx ,testy ,test_size=0.50,random_state=777)


# Split the data (i.e. features and target) into 70% train, 15% validate, and 15% test; Use Random Seed 777



## Splitting the Train data to Train and Validate Sets

## Nearest neighbor classification with L2 distance

To compute nearest neighbors in our data set, we need to first be able to compute distances between data points. A natural distance function is _Euclidean distance_: for two vectors $x, y \in \mathbb{R}^d$, their Euclidean distance is defined as 
$$\|x - y\| = \sqrt{\sum_{i=1}^d (x_i - y_i)^2}.$$
Often we omit the square root, and simply compute _squared Euclidean distance_:
$$\|x - y\|^2 = \sum_{i=1}^d (x_i - y_i)^2.$$
For the purposes of nearest neighbor computations, the two are equivalent: for three vectors $x, y, z \in \mathbb{R}^d$, we have $\|x - y\| \leq \|x - z\|$ if and only if $\|x - y\|^2 \leq \|x - z\|^2$.

## 1. Nearest neighbor classification with L2 distance

Write a function, **NN_L2**, which takes as input the training data (`trainx` and `trainy`) and the test points (`evalx`) and predicts labels for these test points using 1-NN classification. These labels should be returned in a `numpy` array with one entry per test point. For **NN_L2**, the L2 norm should be used as the distance metric.

In [552]:
def l2_distance(x1,x2):
    return np.sum((x1-x2)**2)

In [553]:
def NN_L2(trainx, trainy, evalx):
    
    nn_labels = []
    
    for points in evalx:

        distances = [l2_distance(x,points) for x in trainx]
        nn = np.argsort(distances)[:1]
        
        labels = trainy[nn]
       
        nn_labels.append(labels)
 

    return nn_labels
    ### END CODE HERE ###

## 2. K-Nearest neighbor classification with L2 distance

Write a function, **KNN_L2**, which takes as input the training data (`trainx` and `trainy`), the test points (`evalx`), and the value of **K** (integer) and predicts labels for these test points using K-NN classification. These labels should be returned in a `numpy` array with one entry per test point.

In [554]:
def KNN_L2(trainx, trainy, evalx, k):
    knn_labels = []
    
    for points in evalx:

        distances = [l2_distance(x,points) for x in trainx]
        knn = np.argsort(distances)[:k]
        
        labels = trainy[knn]

        vote = mode(labels)
        knn_labels.append(vote)
    

    return knn_labels

## 3. Nearest neighbor classification with L1 distance

We now compute nearest neighbors using the L1 distance (sometimes called *Manhattan Distance*).

Write a function, **NN_L1**, which again takes as input the arrays `trainx`, `trainy`, and `evalx`, and predicts labels for the test points using 1-nearest neighbor classification. For **NN_L1**, the L1 distance metric should be used. As before, the predicted labels should be returned in a `numpy` array with one entry per test point.

Notice that **NN_L1** and **NN_L2** may well produce different predictions on the test set.

In [555]:
def l1_distance(x1,x2):
    return np.sum(np.abs(x1-x2))

In [556]:
def NN_L1(trainx, trainy, evalx):
    
    nn_labels = []
    
    for points in evalx:

        distances = [l1_distance(x,points) for x in trainx]
        nn = np.argsort(distances)[:1]
        labels = trainy[nn]
       
        nn_labels.append(labels)
 

    return nn_labels
    ### END CODE HERE ###

## 4. K-Nearest neighbor classification with L1 distance

Write a function, **KNN_L1**, which takes as input the training data (`trainx` and `trainy`), the test points (`evalx`), and the value of **K** (integer) and predicts labels for these test points using K-NN classification and L1 distance metric. These labels should be returned in a `numpy` array with one entry per test point.

In [557]:
def KNN_L1(trainx, trainy, evalx, k):
    
    knn_labels = []
    
    for points in evalx:

        distances = [l1_distance(x,points) for x in trainx]
        knn = np.argsort(distances)[:k]
        
        labels = trainy[knn]

        vote = mode(labels)

        knn_labels.append(vote)
    

    return knn_labels
    ### END CODE HERE ###

## 5. K-Nearest neighbor classifier

Write a function, **KNN**, which takes as input the training data (`trainx` and `trainy`), the test points (`evalx`), the value of **K** (integer), and a parameter for deciding the distance metric to be used (for example 1 for L1 and 2 for L2) and predicts labels for these test points using KNN classification. These labels should be returned in a `numpy` array with one entry per test point.

In [558]:
def KNN(trainx, trainy, evalx, K, dist_metric=2):
    # output: an np.array of the predicted values for testy 
    
    ### START CODE HERE ###
        knn_labels = []
    
        
        for points in evalx:
            if dist_metric == 1:
                distances = [l1_distance(x,points) for x in trainx]
            else:
                distances = [l2_distance(x,points) for x in trainx]

            knn = np.argsort(distances)[:k]

            labels = trainy[knn]

            vote = mode(labels)
   
            knn_labels.append(vote)
    

        return knn_labels
    ### END CODE HERE ###

## 6. Putting it all together

Write code that allows you to select the hyper-parameters (distance measure and the value of K) by calling the KNN classifier with different values of K and either L1 or L2 distance measure. Make sure that you set the hyper-parameters using the validation set and not the test set. You need to systemtically try different values for K in conjunction with a distance measure and tabulate the results (you can do that be craeting a seperate cell and documenting in that cell) and note down the best hyper-parameter settings.

In [559]:
### START CODE HERE ###
nn_predict_l2 = NN_L2(trainx, trainy, valx)
knn_predict_l2 = KNN_L2(trainx, trainy, valx,9)
nn_predict_l1 = NN_L1(trainx, trainy, valx)
knn_predict_l1 = KNN_L1(trainx, trainy, valx, 9)

print(' NN with L2 distance accuracy = ',accuracy_score(valy,nn_predict_l2))

print('KNN with L2 distance accuracy = ',accuracy_score(valy,knn_predict_l2))

print(' NN with L1 distance accuracy = ',accuracy_score(valy,nn_predict_l1))

print('KNN with L1 distance accuracy = ',accuracy_score(valy,knn_predict_l1))


### END CODE HERE ###

 NN with L2 distance accuracy =  0.8953488372093024
KNN with L2 distance accuracy =  0.9534883720930233
 NN with L1 distance accuracy =  0.9418604651162791
KNN with L1 distance accuracy =  0.9651162790697675


# 7. Test errors and the confusion matrix

Once the hyper-parameters have been selected, we now would like to perform a final evaluation on the test set and record the error rates. Also, Write a function, **confusion**, which takes as input the true labels for the test set (that is, `testy`) as well as the predicted labels and returns the confusion matrix. The confusion matrix should be a `np.array` of shape `(10,10)`. Also, record the confusion matrix in your assignment report.

**Note:** Record the cpu time it takes to perform the evaluation on the test set using functions like **time.time()**.

In [560]:
def confusion(testy, testy_fit):
    # inputs: the correct labels, the fitted KNN labels 
    # output: a 10x10 np.array representing the confusion matrix as above
    
    ### START CODE HERE ###
    return confusion_matrix(testy,testy_fit)
    ### END CODE HERE ###

In [561]:
# Code for performing the final evaluation on the test set and generating the confuson matrix.
### START CODE HERE ###
nn_predict_l2 = NN_L2(trainx, trainy, testx)
knn_predict_l2 = KNN_L2(trainx, trainy, testx,9)
nn_predict_l1 = NN_L1(trainx, trainy, testx)
knn_predict_l1 = KNN_L1(trainx, trainy, testx, 9)

print(' NN with L2 distance accuracy = ',accuracy_score(testy,nn_predict_l2))

print('KNN with L2 distance accuracy = ',accuracy_score(testy,knn_predict_l2))

print(' NN with L1 distance accuracy = ',accuracy_score(testy,nn_predict_l1))

print('KNN with L1 distance accuracy = ',accuracy_score(testy,knn_predict_l1))

print(' confusion matrix for NN with L2 distance accuracy \n', confusion(testy, nn_predict_l2))

print('confusion matrix for KNN with L2 distance accuracy \n', confusion(testy, knn_predict_l2))

print(' confusion matrix for NN with L1 distance accuracy \n', confusion(testy, nn_predict_l1))

print('confusion matrix for KNN with L1 distance accuracy \n', confusion(testy, knn_predict_l1))

### END CODE HERE ###

 NN with L2 distance accuracy =  0.8941176470588236
KNN with L2 distance accuracy =  0.9176470588235294
 NN with L1 distance accuracy =  0.9176470588235294
KNN with L1 distance accuracy =  0.9176470588235294
 confusion matrix for NN with L2 distance accuracy 
 [[23  5]
 [ 4 53]]
confusion matrix for KNN with L2 distance accuracy 
 [[22  6]
 [ 1 56]]
 confusion matrix for NN with L1 distance accuracy 
 [[23  5]
 [ 2 55]]
confusion matrix for KNN with L1 distance accuracy 
 [[22  6]
 [ 1 56]]


## 8. Preparing the assignment report

You need to prepare the assignment report and submit your code and report to the Blackboard assignment. You need to record your answers for the following questions in the report:
1. What is the error rate on the validation set for NN_L2?
2. What is the best error rate on the validation set for KNN_L2?
3. What is the error rate on the validation set for NN_L1?
4. What is the best error rate on the validation set for KNN_L1?
5. What is the error rate on the test set?
7. Do you need to normalize data, in general, when using KNN?

8. Do you need to normalize data when using KNN for the given problem? Explain why?

## 9. Extra Stuff

You are invited to try some more ideas as extra work like:
1. Implementing weighted KNN where the vote of a neighbour is scaled down based on its distance from the test point.
2. Implement L_infinity distance measure and use it for classification.

## Points to remember

You need to keep in mind the following points:
1. Use numpy arrays and numpy libraries for efficient computations. 
2. Vectorize the code wherever possible instead of using explicit loops. This will significantly speed-up your code.